# Generated by Django 4.2.3 on 2023-07-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_colaborador',
            field=models.BooleanField(default=False),
        ),
    ]
