# Generated by Django 4.2.3 on 2023-07-16 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_is_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='../static/img/woman_icon.png', upload_to='usuarios'),
        ),
    ]
