# Generated by Django 4.2.3 on 2023-07-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(default='img/user_avatar_profile_icon.png', upload_to='usuarios'),
        ),
    ]
