<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-07-25 21:53
=======
# Generated by Django 4.2.3 on 2023-07-25 20:19
>>>>>>> 7371b795c44399c01e6b0e09de00afb0308af29e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_usuario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
<<<<<<< HEAD
            field=models.ImageField(default='user/user_avatar_profile_icon.png', upload_to='usuarios'),
=======
            field=models.ImageField(default='user_avatar_profile_icon.png', upload_to='usuarios'),
>>>>>>> 7371b795c44399c01e6b0e09de00afb0308af29e
        ),
    ]
