# Generated by Django 4.2.3 on 2023-07-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(default='iconos/default_icon.png', upload_to='articulos'),
        ),
    ]
