# Generated by Django 4.2.3 on 2023-07-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0005_comentario_articulo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
