# Generated by Django 4.2.3 on 2023-07-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='comentarios',
        ),
    ]
