# Generated by Django 4.2.3 on 2023-07-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0008_remove_articulo_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='articulos.comentario'),
        ),
    ]
